give  Sun  4 Apr 11:28:31 AEST 2021: Final submission

diff --git a/girt-branch b/girt-branch
--- a/girt-branch
+++ b/girt-branch
@@ -1,9 +1,17 @@
 #!/bin/dash
+# outputs error message if .girt was not initiated
+if (! test -d .girt)
+then
+    echo "girt-branch: error: girt repository directory .girt not found"
+    exit 1
+fi
+# branch can only be run after first commit
 if (test -z "$(cat .girt/message.txt)") 
 then
     echo "girt-branch: error: this command can not be run until after the first commit"
     exit 1
 fi
+# prints all branch names
 if (test $# -eq 0)
 then
     ls -d .girt/branch/* | sed -e "s/.girt\/branch\///g"
@@ -13,59 +21,66 @@ then
     if (test $1 = '-d')
     then
         echo "girt-branch: error: branch name required"
-        exit
+        exit 1
     fi
+    # ensures branch name is valid
     if (! test $(echo $1 | grep -e '^[a-zA-Z0-9][a-zA-Z0-9_-]*$'))
     then
         echo "girt-branch: error: invalid branch name '$1'"
         exit 1
     fi
+    # checks if branch exists
     if (test -d .girt/branch/$1)
     then
         echo "girt-branch: error: branch '$1' already exists"
-        exit
+        exit 1
     fi
+    # creates branch
     mkdir .girt/branch/$1
     cp .girt/message.txt .girt/branch/$1/message.txt
 elif (test $# -eq 2 && test $1 = '-d')
 then
+    # can not delete master branch
     if (test $2 = 'master')
     then
         echo "girt-branch: error: can not delete branch 'master'"
-        exit
+        exit 1
+    # ensures branch exist
     elif (test -d .girt/branch/$2)
     then
+        # can not delete current branch
         if (test "$(cat .girt/branchname.txt)" = "$2") 
         then
             echo "girt-branch: error: internal error error: Cannot delete branch '$2'"
             exit 1
         fi
+        # ensure branch does not have unmerged changes
         commitNo=$(cat .girt/branch/$2/message.txt | cut -d " " -f1 | tail -n 1)
 
         curCommitNo=$(cat .girt/message.txt | cut -d " " -f1 | tail -n 1)
 
         currPath=$(tac .girt/commitPath/$curCommitNo | cut -d " " -f1 )
         mergePath=$(tac .girt/commitPath/$commitNo | cut -d " " -f1 )
-        comCurr=""
+        commonCommit=-1
 
         for comCurr in $currPath
         do
             for comMerg in $mergePath
             do
-                if (test $comCurr = $comMerg)
+                if (test $comCurr -eq $comMerg)
                 then
-                    commonCommit="$comCurr"
+                    commonCommit=$comCurr
                     break
                 elif (test $comCurr -gt $comMerg)
                 then
                     break
                 fi
             done
-            if (test "$comCurr"!="") then
+            if (test $commonCommit -ne -1) then
                 break
             fi
         done
-
+        # deletes branch if it has no unmerged changes
         if (test "$commonCommit" -eq "$commitNo")
         then
             rm -r .girt/branch/$2
@@ -76,6 +91,7 @@ then
         exit 1
     fi
     echo "girt-branch: error: branch '$2' doesn't exist"
+# invalid usage
 else
     echo "usage: girt-branch [-d] <branch>"
 fi
diff --git a/girt-checkout b/girt-checkout
--- a/girt-checkout
+++ b/girt-checkout
@@ -1,115 +1,149 @@
 #!/bin/dash
+# outputs error message if .girt was not initiated
+if (! test -d .girt)
+then
+    echo "girt-checkout: error: girt repository directory .girt not found"
+    exit 1
+fi
+
+# improper usage
 if (test $# -ne 1)
 then
     echo "usage: girt-checkout <branch>"
     exit
 fi
-
 current=$(cat .girt/branchname.txt)
+
+# checkout to current branch
 if (test "$current" = "$1")
 then
     echo "Already on '$1'"
     exit
 fi
 
+# error for non-existent branch
 if (! test -d .girt/branch/$1)
 then
     echo "girt-checkout: error: unknown branch '$1'"
     exit
 fi
 
-count=$(cat .girt/message.txt | cut -d " " -f1 | tail -n 1)
-newcount=$(cat .girt/branch/$1/message.txt | cut -d " " -f1 | tail -n 1)
+# get last commit number for current branch and checkout branch
+currCom=$(cat .girt/message.txt | cut -d " " -f1 | tail -n 1)
+checkoutCom=$(cat .girt/branch/$1/message.txt | cut -d " " -f1 | tail -n 1)
 
+# bool for if checkout would lead to overwrite
 overwritten=0
 
-for file in .girt/repository/$count/*
+# check for overwrite error
+for file in .girt/repository/$currCom/*
 do
-    # ensures each file echoes once upon overwrite error
-    echoamount=0
-    filename=$(echo $file | sed "s|.girt/repository/$count/||")
-    if (test -f .girt/repository/$newcount/$filename && ! cmp -s ".girt/repository/$newcount/$filename" "$file")
+    filename=$(echo $file | sed "s|.girt/repository/$currCom/||")
+    # get all existing files that are not the same in both commits
+    if (test -f .girt/repository/$checkoutCom/$filename && ! cmp -s ".girt/repository/$checkoutCom/$filename" "$file")
     then
+        # if the file has been changed since the last commit output overwrite error
         if (test -f $filename && ! cmp -s "$filename" "$file")
         then
+            # ensures error message is printed once
             if (test $overwritten -eq 0)
             then
                 overwritten=1
                 echoamount=1
                 echo "girt-checkout: error: Your changes to the following files would be overwritten by checkout:"
+                # all overwritten files are stored in text file
                 echo "$filename" >>.girt/overwritten.txt
             else
+                # all overwritten files are stored in text file
                 echo "$filename" >>.girt/overwritten.txt
             fi
         fi
-        if (test -f .girt/index/$filename && test $echoamount -eq 0 && ! cmp -s ".girt/index/$filename" "$file")
+        if (test -f .girt/index/$filename && ! cmp -s ".girt/index/$filename" "$file")
         then
+            # ensures error message is printed once
             if (test $overwritten -eq 0)
             then
                 overwritten=1
                 echo "girt-checkout: error: Your changes to the following files would be overwritten by checkout:"
+                # all overwritten files are stored in text file
                 echo "$filename" >>.girt/overwritten.txt
             else
+                # all overwritten files are stored in text file
                 echo "$filename" >>.girt/overwritten.txt
             fi
         fi
     fi
 done
-files=$(diff -r . .girt/repository/$count/ | grep "Only in .: " | sed "s/Only in .://")
+
+# gets all files that has not been committed in current directory
+files=$(diff -r . .girt/repository/$currCom/ | grep "Only in .: " | sed "s/Only in .://")
 for file in $files
 do
-    echoamount=0
-    if (test -f .girt/repository/$newcount/$file)
+    # if the file is in checkout commit output overwrite error
+    if (test -f .girt/repository/$checkoutCom/$file)
     then
+        # ensures error message is printed once
         if (test $overwritten -eq 0)
         then
             overwritten=1
-            echoamount=1
             echo "girt-checkout: error: Your changes to the following files would be overwritten by checkout:"
+            # all overwritten files are stored in text file
             echo "$file" >>.girt/overwritten.txt
         else
+            # all overwritten files are stored in text file
             echo "$file" >>.girt/overwritten.txt
         fi
     fi
 done
-files=$(diff -r .girt/index/ .girt/repository/$count/ | grep "Only in .girt/index/: " | sed "s|Only in .girt/index/:||")
+
+# gets all files that has not been committed in index
+files=$(diff -r .girt/index/ .girt/repository/$currCom/ | grep "Only in .girt/index/: " | sed "s|Only in .girt/index/:||")
 for file in $files
 do
-    echoamount=0
-    if (test -f .girt/repository/$newcount/$file)
+    # if the file is in checkout commit output overwrite error
+    if (test -f .girt/repository/$checkoutCom/$file)
     then
+        # ensures error message is printed once
         if (test $overwritten -eq 0)
         then
             overwritten=1
-            echoamount=1
             echo "girt-checkout: error: Your changes to the following files would be overwritten by checkout:"
+            # all overwritten files are stored in text file
             echo "$file" >>.girt/overwritten.txt
         else
+            # all overwritten files are stored in text file
             echo "$file" >>.girt/overwritten.txt
         fi
     fi
 done
 if (test $overwritten -eq 1)
 then
+    # prints all files that would be overwritten
     cat .girt/overwritten.txt | sort | uniq
     rm .girt/overwritten.txt
-    exit
+    exit 1
 fi
 
+# saves all commit into current branch directory if there had been any commits
 if (! cmp -s ".girt/message.txt" ".girt/branch/$current/message.txt") 
 then
     cp .girt/message.txt .girt/branch/$current/message.txt 2>/dev/null
     cp .girt/message.txt .girt/branch/$current/message.txt 2>/dev/null
 fi
 
+# if branches are on different commits, files in current directory and index are updated
+# to the files in the new branch
 if (! cmp -s ".girt/message.txt" ".girt/branch/$1/message.txt")
 then
+    # deleted files remain deleted upon checkout
     echo -n "" >_deletedCurDir
     echo -n "" >_deletedIndex
 
-    for file in .girt/repository/$count/*
+    # deletes all files that are different between the two branches
+    # and replace them with files in checkout branch
+    for file in .girt/repository/$currCom/*
     do
-        filename=$(echo $file | sed "s|.girt/repository/$count/||")
+        filename=$(echo $file | sed "s|.girt/repository/$currCom/||")
         if (test -f $filename)
         then
             rm $filename 2>/dev/null
@@ -126,11 +160,11 @@ then
 
     cp .girt/branch/$1/message.txt .girt/message.txt 2>/dev/null
 
-    count=$(cat .girt/message.txt | cut -d " " -f1 | tail -n 1)
+    currCom=$(cat .girt/message.txt | cut -d " " -f1 | tail -n 1)
 
-    for file in .girt/repository/$count/*
+    for file in .girt/repository/$currCom/*
     do
-        filename=$(echo $file | sed "s|.girt/repository/$count/||")
+        filename=$(echo $file | sed "s|.girt/repository/$currCom/||")
         if (! cat _deletedCurDir | egrep -q "^$filename$") 
         then
             cp $file $filename 2>/dev/null
@@ -144,6 +178,7 @@ then
     rm _deletedCurDir
     rm _deletedIndex
 fi
+# change branch name to checkout branch
 echo "$1" >.girt/branchname.txt
 
 echo "Switched to branch '$1'"
diff --git a/girt-commit b/girt-commit
--- a/girt-commit
+++ b/girt-commit
@@ -1,13 +1,22 @@
 #!/bin/dash
+# outputs error message if .girt was not initiated
+if (! test -d .girt)
+then
+    echo "girt-commit: error: girt repository directory .girt not found"
+    exit 1
+fi
 
+# ensures number of arguments is valid
 if (test $# -gt 3 || test $# -lt 2) 
 then
     echo "usage: girt-commit [-a] -m commit-message"
     exit 1
 fi
 
+# gets total amount of commits
 count=$(ls .girt/repository/ | wc -l)
 
+# causes all files already in the index to have their contents from the current directory added to the index before the commit
 if (test $1 = '-a')
 then
     for files in .girt/index/*
@@ -17,13 +26,16 @@ then
     done
 fi
 
+# bool to see if there is anything to commit
 change=0
 
+# if there is a file in index but not in repository there is something to commit
 if (test $(diff -q ".girt/index/" ".girt/repository/$((count-1))/" | wc -l) -gt 0) > /dev/null 2>&1
 then
     change=1
 fi
 
+# checks if there is anything to commit
 for files in .girt/index/*
 do
     fileName=$(echo $files | sed "s/.girt\/index\//.girt\/repository\/$((count - 1))\//")
@@ -37,6 +49,7 @@ do
     fi
 done
 
+# checks if girt-commit usage is correct
 if (test $1 = "-m")
 then
     if (test $# -ne 2)
@@ -55,14 +68,17 @@ then
     message="$count $3"
 fi
 
+# exits if there is nothing to commit
 if (test $change -eq 0)
 then
     echo "nothing to commit"
     exit
 fi
 
+# store message in file
 echo $message >>.girt/message.txt
 
+# creates a directory in repository that stores all files in each commit
 mkdir .girt/repository/$count
 
 for files in .girt/index/*
@@ -71,6 +87,7 @@ do
     cp "$files" "$fileName" > /dev/null 2>&1
 done
 
+# copy files into commitPath directory where all path of commits are stored
 cp .girt/message.txt .girt/commitPath/$count
 
 echo "Committed as commit $count"
diff --git a/girt-log b/girt-log
--- a/girt-log
+++ b/girt-log
@@ -1,2 +1,9 @@
 #!/bin/dash
+# outputs error message if .girt was not initiated
+if (! test -d .girt)
+then
+    echo "girt-log: error: girt repository directory .girt not found"
+    exit 1
+fi
+# prints all commit messages
 tac .girt/message.txt
diff --git a/girt-merge b/girt-merge
--- a/girt-merge
+++ b/girt-merge
@@ -1,4 +1,11 @@
 #!/bin/dash
+# outputs error message if .girt was not initiated
+if (! test -d .girt)
+then
+    echo "girt-merge: error: girt repository directory .girt not found"
+    exit 1
+fi
+# checks girt-merge usage
 if (test $# -eq 1)
 then
     if (test $1 = '-m')
@@ -9,12 +16,13 @@ then
     echo "girt-merge: error: empty commit message"
     exit 1
 fi
-
 if (test $# -ne 3)
 then
     echo "usage: girt-merge <branch|commit> -m message"
     exit 1
 fi
+
+# get merge message and branch/commit number depending on argument order
 if (test "$1" = '-m')
 then
     message=$2
@@ -28,6 +36,7 @@ else
     exit 1
 fi
 
+# get commit number for merge
 if (test $(echo $commit | grep '[0-9]+'))
 then
     if (! test -d ".girt/repository/$commit")
@@ -48,12 +57,16 @@ else
     fi
     commitNo=$(tail -n 1 .girt/branch/$commit/message.txt | cut -d " " -f1 )
 fi
+# get last commit number of current branch 
 curCommitNo=$(tail -n 1 .girt/message.txt | cut -d " " -f1 )
 
+# get commit path for both the current branch's commit and the provided commit
 currPath=$(tac .girt/commitPath/$curCommitNo | cut -d " " -f1 )
 mergePath=$(tac .girt/commitPath/$commitNo | cut -d " " -f1 )
+
 commonCommit=-1
 
+# get the last common commit
 for comCurr in $currPath
 do
     for comMerg in $mergePath
@@ -72,12 +85,14 @@ do
     fi
 done
 
+# if the provided commit number is the same as the common commit number then the branch is already up to date
 if (test "$commonCommit" -eq "$commitNo")
 then
     echo "Already up to date"
     exit
 fi
 
+# store all files that were changed since the common commit to the provided commit into changes.txt
 for file in .girt/repository/$commitNo/*
 do
     filename=$(echo "$file" | sed "s|.girt/repository/$commitNo/||")
@@ -87,6 +102,7 @@ do
     fi
 done
 
+# if the current directory has changes to the same files since the common commit then output merge conflict error
 for file in .girt/repository/$curCommitNo/*
 do
     filename=$(echo "$file" | sed "s|.girt/repository/$curCommitNo/||")
@@ -101,9 +117,11 @@ do
     fi
 done
 
+# if the common commit is the last current commit, a fast forward should occur
 if (test "$curCommitNo" -eq "$commonCommit")
 then
     cp .girt/commitPath/$commitNo .girt/message.txt
+    # add files to current directory and index
     for file in $(cat .girt/changes.txt)
     do
         cp .girt/repository/$commitNo/$file $file
@@ -113,6 +131,8 @@ then
     rm .girt/changes.txt
     exit
 fi
+
+# add files to current directory and index and commit changes
 for file in $(cat .girt/changes.txt)
 do
     cp .girt/repository/$commitNo/$file $file
diff --git a/girt-rm b/girt-rm
--- a/girt-rm
+++ b/girt-rm
@@ -1,7 +1,18 @@
 #!/bin/dash
+# outputs error message if .girt was not initiated
+if (! test -d .girt)
+then
+    echo "girt-rm: error: girt repository directory .girt not found"
+    exit 1
+fi
+# bool for force and cached
 force=0
 cached=0
+
+# get last commit
 count=$(cat .girt/message.txt | cut -d " " -f1 | tail -n 1)
+
+# checks for --force and --cached
 for option in $@
 do
     if (test $option = '--force')
@@ -12,23 +23,35 @@ do
         cached=1
     fi
 done
+
+# checks for all possible error messages
 for files in $@
 do
-    if (! test $files = '--cached' && ! test $files = '--force' && test -f $files)
+    # gets files in argument and test if file exist in index or current directory
+    if (! test $files = '--cached' && ! test $files = '--force' && ( test -f $files || test -f .girt/index/$files))
     then
+        # force option is not called
         if (! test $force -eq 1)
         then
-            if (test $count -eq -1 || ! cmp -s ".girt/index/$files" ".girt/repository/$count/$files" \
-                && ! (cmp "$files" ".girt/index/$files" && test $cached -eq 1)) > /dev/null 2>&1
+            # if there has not been any commits or file in index is different to the file in repository
+            if (test $count -eq -1 || ! cmp -s ".girt/index/$files" ".girt/repository/$count/$files") > /dev/null 2>&1
             then
-                if (cmp -s "$files" ".girt/index/$files") 2>/dev/null
+                # if the file in index and current directory are the same and --cached is called then
+                # do not call exit
+                if (cmp "$files" ".girt/index/$files" && test $cached -eq 1) > /dev/null 2>&1
+                then
+                    :
+                # if file in index and current directory are the same
+                elif (cmp -s "$files" ".girt/index/$files") > /dev/null 2>&1
                 then
                     echo "girt-rm: error: '$files' has staged changes in the index"
                     exit 1
+                # if file is not in index
                 elif (! test -f ".girt/index/$files")
                 then 
                     echo "girt-rm: error: '$files' is not in the girt repository"
                     exit 1
+                # if file in index is different to file in current directory and repository
                 else 
                     echo "girt-rm: error: '$files' in index is different to both to the working file and the repository"
                     exit 1
@@ -36,25 +59,34 @@ do
             fi
             if (test $cached -eq 0)
             then
-                if (test $count -eq -1 || ! cmp -s "$files" ".girt/index/$files")  > /dev/null 2>&1
+                # if there has not been any commits or file in index and current directory are not the same
+                if (test $count -eq -1 || ! cmp -s "$files" ".girt/index/$files") > /dev/null 2>&1
                 then
+                    # if file is not in repository
                     if (! test -f ".girt/repository/$count/$files")
                     then
                         echo "girt-rm: error: '$files' is not in the girt repository"
                         exit 1
+                    # if file in current directory is not the same in repository
                     else
                         echo "girt-rm: error: '$files' in the repository is different to the working file"
                         exit 1
                     fi
                 fi
             fi
-        elif (test $force -eq 1 && ! test -f ".girt/index/$files")
-        then
+        elif (test $force=1 && ! test -f .girt/index/$files)
+        then 
             echo "girt-rm: error: '$files' is not in the girt repository"
             exit 1
         fi
+    # if file does not exist then output error
+    elif (! test $files = '--cached' && ! test $files = '--force' && ! test -f $files && ! test -f .girt/index/$files)
+    then 
+        echo "girt-rm: error: '$files' is not in the girt repository"
+        exit 1
     fi
 done
+# delete files
 for files in $@
 do
     if (! test $files = '--cached' && ! test $files = '--force')
diff --git a/girt-show b/girt-show
--- a/girt-show
+++ b/girt-show
@@ -1,22 +1,44 @@
 #!/bin/dash
+# outputs error message if .girt was not initiated
+if (! test -d .girt)
+then
+    echo "girt-show: error: girt repository directory .girt not found"
+    exit 1
+fi
+if (test $# -ne 1)
+then
+    echo "heasdllo"
+    echo "usage: girt-show <commit>:<filename>"
+    exit 1
+fi
+# gets commit number and file
 commitNo=$(echo $1 | cut -d ':' -f 1)
 fileName=$(echo $1 | cut -d ':' -f 2)
-if (! test $commitNo -ge 0) > /dev/null 2>&1
+# invalid commit number
+if (! test $commitNo -ge 0 && ! test -z $commitNo) > /dev/null 2>&1
 then
-    if (! cat .girt/index/$fileName) 2>/dev/null
-    then
-        echo "girt-show: error: '$fileName' not found in index"
-        exit 1
-    fi
+    echo "usage: girt-show <commit>:<filename>"
+    exit 1
+# commit not in repository
+elif (! test -d .girt/repository/$commitNo && ! test -z $commitNo) 2>/dev/null
+then
+    echo "girt-show: error: unknown commit '$commitNo'"
+    exit 1
 else
-    if (! cat .girt/repository/$commitNo/$fileName) 2>/dev/null
+    # prints file content from index if no commit number provided
+    if (test -z $commitNo)
     then
-        if (! test -d .girt/repository/$commitNo)
+        if (! cat .girt/index/$fileName) 2>/dev/null
         then
-            echo "girt-show: error: unknown commit '$commitNo'"
-        else
-            echo "girt-show: error: '$fileName' not found in commit $commitNo"
+            # if file does not exist output error
+            echo "girt-show: error: '$fileName' not found in index"
+            exit 1
         fi
+    # prints content of file in repository
+    elif (! cat .girt/repository/$commitNo/$fileName) 2>/dev/null
+    then
+        # if file does not exist output error
+        echo "girt-show: error: '$fileName' not found in commit $commitNo"
         exit 1
     fi
 fi
diff --git a/girt-status b/girt-status
--- a/girt-status
+++ b/girt-status
@@ -1,6 +1,14 @@
 #!/bin/dash
+# outputs error message if .girt was not initiated
+if (! test -d .girt)
+then
+    echo "girt-status: error: girt repository directory .girt not found"
+    exit 1
+fi
+# create file where output is stored
 echo -n "" >.girt/status.txt
 count=$(cat .girt/message.txt | cut -d " " -f1 | tail -n 1)
+# get status of all files in current directory
 for files in `ls`
 do
     if (! test -f .girt/index/$files)
@@ -29,6 +37,7 @@ do
         echo "$files - same as repo" >>.girt/status.txt
     fi
 done
+# get status of all files in repository but not in current directory
 deleted=$(find ".girt/repository/$count/" "." "." -printf '%P\n' | sort | uniq -u)
 for files in $deleted
 do
@@ -44,6 +53,7 @@ do
         echo "$files - deleted" >>.girt/status.txt
     fi
 done
+# get status of all files in index but not in current directory
 deleted=$(find ".girt/index/" "." "." -printf '%P\n' | sort | uniq -u)
 for files in $deleted
 do
@@ -53,4 +63,5 @@ do
         echo "$file - added to index, file deleted" >>.girt/status.txt
     fi
 done
+# prints status
 cat ".girt/status.txt" | sort
